name: 722 issue replicated

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest','macos-latest']
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      # Any second call to setup-go with cache enabled triggers the issue
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true
